### ISSUE TITLE
Split up Chapter 2

### ISSUE THREAD

**Issue by superjax** [byu-magicc/lie_groups#4]
Right now, chapter 2 is becoming a bit of beast.  I propose separating chapter 2 into several chapters:

 1. SO(2) Notation and Kinetmatics
 2. Gradient Descent on SO(2)
 3. Differential Equation Solvers for SO(2)
 4. PID Control on SO(2)
 5. Optimal Control on SO(2)
 6. State Estimation on SO(2)

@plusk01, @jerelbn, @randybeard, @dpkoch, What do you think?

**Comment by plusk01** [comment]
I agree that it's getting too big, and was also just wondering this. I was thinking splitting it into chapters like you suggest, and even creating directories for each "section". So the TOC would look something like:

```
0. Introduction and Motivation

SECTION I: SO(2)

 1. Notation and Kinetmatics
 2. Gradient Descent
 3. Differential Equation Solvers
 4. PID Control
 5. Optimal Control
 6. State Estimation

SECTION II: SE(2)

...

```

**Comment by randybeard** [comment]
I like that idea.  It will be easier to manage.

Another option is to parse the topics in the other direction

SECTION I: Notation and Kinematics
	- SO(2)
	- SE(2)
	…

SECTION II: GRADIENT DESCENT
	- SO(2)

Etc.

On June 23, 2018 at 12:40:10 PM, Parker Lusk (notifications@github.com) wrote:

I agree that it's getting too big, and was also just wondering this. I was thinking splitting it into chapters like you suggest, and even creating directories for each "section". So the TOC would look something like:

0. Introduction and Motivation

SECTION I: SO(2)

 1. Notation and Kinetmatics
 2. Gradient Descent
 3. Differential Equation Solvers
 4. PID Control
 5. Optimal Control
 6. State Estimation

SECTION II: SE(2)

...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

—
Randal W. Beard
Professor, Electrical and Computer Engineering
Brigham Young University
(801) 422-8392, beard@byu.edu
