### ISSUE TITLE
Need `environment.yml` or `requirements.txt` and `apt.txt`

### ISSUE THREAD

**Issue by DevonMorris** [byu-magicc/lie_groups#9]
There are some dependencies missing when you try to run the code in binder. 

see http://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder

If we add these dependencies, binder will go ahead and install them for us.

Short list of things we need (off the top of my head)
- numpy
- cvxpy
- ffmpeg

add more as you guys see fit.

@plusk01 @superjax

**Comment by plusk01** [comment]
I left out the `cvxpy` dependency because of an issue with one of its dependencies, `ecos`. `ecos` is not correctly depending on `numpy`, so when binder tries to install everything in `requirements.txt` at once, it fails. This should be hopefully be fixed soonish, according to [this PR](https://github.com/embotech/ecos-python/issues/8).

In the interim, if you *really* want `cvxpy` in the notebook on binder, you can just install it manually (i.e., in a notebook Python cell, run `!pip install cvxpy`). This works because `numpy` is already installed at this point.
